# Replace these variables
title: "Buzzwords"
description: "Topic Modelling on GPU"
url: "https://bumble-tech.github.io/buzzwords/"
repo_url: "https://github.com/bumble-tech/buzzwords/"
github_username: "Steeeephen"
repository: "bumble-tech/buzzwords"

sidebar:
  - documentation
  - info
  - installation
  - tutorial
logo_url: "images/buzzwords.png"

# Build settings
plugins:
- jemoji
- jekyll-seo-tag